" Hybrid line number
set relativenumber number

" Turn syntax highlighting on.
syntax enable
syntax on

" Indent, tab
set tabstop=4
set shiftwidth=4
set autoindent

" Highlight the line at cursor
set cursorline

" Install vim-plug
let data_dir = '~/.vim'
if empty(glob(data_dir . '/autoload/plug.vim'))
  silent execute '!curl -fLo '.data_dir.'/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" Install Plugins
call plug#begin()

Plug 'dracula/vim', { 'as': 'dracula' }

Plug 'tpope/vim-surround'

Plug 'terryma/vim-multiple-cursors'

call plug#end()

" Activate theme
if !empty(glob('~/.vim/plugged/dracula'))
	colorscheme dracula
endif
